apiVersion: batch/v1
kind: Job
metadata:
  generateName: free-job-
  namespace: free-service
spec:
  template:
    spec:
      containers:
      - name: free-job-container
        image: maxtuecke/cs498-mp12:latest
        resources:
          limits:
            cpu: 0.9
        env:
        - name: DATASET
          value: "mnist"
        - name: TYPE
          value: "ff"
      restartPolicy: Never