apiVersion: batch/v1
kind: Job
metadata:
  generateName: premium-job-
  namespace: default
spec:
  containers:
  - name: premium-job-container
    image: maxtuecke/cs498-mp12
    resources:
      limits:
        cpu: 0.9
    env:
    - name: DATASET
      value: "kmnist"
    - name: TYPE
      value: "cnn"